### ISSUE TITLE
Adapting driver to RA and DEC axis guiding through PHD2

### ISSUE THREAD

**Issue by Pedroscope** [sergio1990/sh-simple-focuser#1]
Is it possible to use this driver to control RA and DEC axis using 2828BYJ-48 motor with a ULN2003 controller?

**Comment by sergio1990** [comment]
Excuse me, I just saw this opened issue and for sure it might be irrelevant at the moment, but want to close the loop anyway. There are several points that make this driver as well as the hardware not suitable for the RA and DEC axis guiding:

1. The 2828BYJ-48 motor has too low torque to move the mount with the telescope. Even for the focuser device, I believe it works for me almost at the maximum of its capabilities. It's better to use NEMA17 motors with, for instance, TMC drivers.
2. I'm afraid it's not possible to use this driver as-is - it's specifically written for controlling the focuser device. For controlling RA/DEC axis we need to implement another ASCOM interface - `ITelescopeV3` - which provides a specific set of methods for telescope control. One day I've found [this](https://github.com/kevinferrare/arduino-st4) repo which can be used as an example.
