### ISSUE TITLE
Error while installing the ASCOM Driver

### ISSUE THREAD

**Issue by jugal2001** [sergio1990/sh-simple-focuser#2]
I ran the script using inno and got the below error.

![Screenshot 2024-03-01 020213](https://github.com/sergio1990/sh-simple-focuser/assets/50669199/9a4b1a7a-3672-47b8-a428-ce5765d35073)
I'd appreciate any help with this, thanks.

**Comment by sergio1990** [comment]
In DM we've figured out that the driver's DLL has to be built first before compiling the installer. The repo doesn't include any pre-built resources.
